services:
  go-api-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api-proxy-prod
    restart: always
    ports:
      - "80:80"
    environment:
      # Production backend API
      BACKEND_HOST: ${BACKEND_HOST:-https://exp.co2e.cc}
      
      # Server configuration
      PORT: ${PORT:-80}
      
      # Whitelist configuration
      WHITELIST_FILE: ${WHITELIST_FILE:-whitelist.json}
      
      # HTTP timeout
      HTTP_TIMEOUT: ${HTTP_TIMEOUT:-30}
    volumes:
      # Production whitelist file
      - ./whitelist.json:/app/whitelist.json:ro
      
      # Optional: Persistent logs
      - ./logs:/app/logs
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 128M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates here
      # - ./ssl:/etc/nginx/ssl:ro
    networks:
      - proxy-network
    depends_on:
      - go-api-proxy
    profiles:
      - with-nginx

networks:
  proxy-network:
    driver: bridge